server:
  port: 9094
spring:
  application:
    name: report-service
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
resliance4j.retry:
  instances:
    customergetall:
      maxRetryAttempts: 5
billing:
  app: This is billing App Reporting Service default