server:
  port: 9094
spring:
  application:
    name: report-service
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
resilience4j.retry:
  instances:
    allCustomer:
      maxAttempts: 3
      waitDuration: 10s
      enableExponentialBackoff: true
resilience4j.circuitbreaker:
  instances:
    default:
      minimumNumberOfCalls: 25

resilience4j.timelimiter:
  instances:
    default:
      timeoutDuration: 2s

resilience4j.ratelimiter:
  instances:
    myratelimit:
      limitForPeriod: 3
      limitRefreshPeriod: 10s
billing:
  app: This is billing App Reporting Service defaulttest