server:
  port: 9094
spring:
  application:
    name: report-service
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
resilience4j.retry:
  instances:
    allCustomer:
      maxAttempts: 3
      waitDuration: 10s
      enableExponentialBackoff: true
resilience4j.circuitbreaker:
  instances:
    default:
      minimumNumberOfCalls: 10
      waitDurationInOpenState: 120s
      maxWaitDurationInHalfOpenState: 120s
billing:
  app: This is billing App Reporting Service default