server:
  port: 9094
spring:
  application:
    name: report-service
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
resilience4j.retry:
  instances:
    default:
      maxAttempts: 5
#      retryExceptions:
#        - com.itgarden.exception.RetryException
#      ignoreExceptions:
#        - com.itgarden.exception.IgnoreException
billing:
  app: This is billing App Reporting Service default