#spring.application.name=service-registry
#server.port=8761
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
server:
  port: 8761
spring:
  application:
    name: service-registry
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
billing:
  app: This is billing App Registry Service default